import { loadLocalEnv } from "./env-loader.js";

export interface SecureMcpTunnelConfig {
  tunnelId: string;
  runtimeKey?: string;
  command: string;
  args: string[];
}

/**
 * Secure MCP Tunnel transport configuration.
 *
 * tunnelId identifies the configured tunnel. runtimeKey is an optional
 * injected credential from the tunnel runtime. It is not an API key and is
 * not expected to be manually generated by users.
 */
export function createTunnelConfigFromEnv(): SecureMcpTunnelConfig {
  loadLocalEnv();

  return {
    tunnelId: requireEnv("OPENAI_MCP_TUNNEL_ID"),
    runtimeKey: process.env.OPENAI_MCP_RUNTIME_KEY,
    command: process.env.OMP_MCP_COMMAND ?? "omp-chatgpt-web-mcp",
    args: [],
  };
}

function requireEnv(name: string): string {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required for Secure MCP Tunnel mode.`);
  return value;
}
